sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jeckson/react-docker-test -f Dockerfile.dev .

scripts:
  - docker run -e CI=true jeckson/react-docker-test npm run test -- --coverage

after_success:
  - echo "Test success"

deploy:
  provider: gae
  keyfile: nodal-thunder-337305-0587904030f5.json
  project: nodal-thunder-337305
  skip_cleanup: true
  default: true
  on:
    all_branches: true